### ISSUE TITLE
PHP Warning: include(/var/www/app/app/../plugins/Wiki/Template/user/sidebar.php): failed to open stream: No such file or directory in /var/www/app/app/Core/Template.php on line 83

### ISSUE THREAD

**Issue by ketigid** [funktechno/kanboard-plugin-wiki#2] opened 2018-02-22 03:21 UTC
Hi, I encountered this error in my logs. Is there a missing file in the installation?

**Comment by lastlink** [comment] 2018-02-22 04:10
could you give more information on your kanboard installation? window/linux/mac
what kind of database that you are using.

**Comment by lastlink** [comment] 2018-02-22 04:15
also you could try uninstalling from the plugins page and reinstalling, I noticed that I left the debugger on & I disabled that in version 0.2.3. the warning doesn't look like an error.

**Comment by ketigid** [comment] 2018-02-26 00:55
I can't re-produce the error reliably. Let me try to figure this out first. Maybe you can close this issue. Thanks.

**Comment by jncruces** [comment] 2018-03-08 14:01
Hi, I have this problem too. 

The problem is in Plugin.php at root of the plugin. In line 36 the code is:

`        $this->template->hook->attach('template:user:sidebar:actions', 'wiki:user/sidebar');
`

For now i commented this line. 

Thanks.

**Comment by lastlink** [comment] 2018-03-08 20:47
could you give more info like what page that you are on when this occurs?

**Comment by jncruces** [comment] 2018-03-09 06:46
Yes. When I access to any user profile the error shows at the end of the left sidebar. 

![2018-03-09 07_43_45- 3 juan natera](https://user-images.githubusercontent.com/5741415/37194260-aabd2b4c-236d-11e8-8a2c-8e8d0f75d810.png)

My Kanboard version is the 1.2.1 
Wiki versión is Version 0.2.3

The plugin.php file is attaching the user/sidebar template but it not exists on templates folder.

**Comment by lastlink** [comment] 2018-03-09 21:57
what database are you using? sqlite, mysql, or postgress?

**Comment by jncruces** [comment] 2018-03-09 22:41
I'm using mysql. 

The code references a template that not exists. I think that the database is not relevant here.

**Comment by lastlink** [comment] 2018-03-10 02:56
release 0.2.4 should fix this bug. Wait for the plugins list to update or download from the releases https://github.com/funktechno/kanboard-plugin-wiki/releases/download/0.2.4-alpha/Wiki-0.2.4.zip. I was unable to have this error appear so I am unable to consistently test this.

**Comment by lastlink** [comment] 2018-03-23 20:32
As no one else has complained about this, I'm marking it as closed.

**Closed by lastlink** 2018-03-23 20:32 UTC
Labels: bug
